name: EAS Android Build
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Build profile (development/preview/production)'
        required: true
        default: 'production'
        type: choice
        options:
          - development
          - preview
          - production

jobs:
  build:
    name: Install and build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: npm install

      - name: Build Android
        run: eas build --local --platform android --profile ${{ inputs.environment }} --non-interactive

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-release-${{ github.ref_name }}
          path: build-*.apk
